# Generated by Django 5.2.5 on 2025-09-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_fotografia_categoria"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ASTROS", "Astros"),
                    ("MUSICA", "Musica"),
                    ("NATUREZA", "Natureza"),
                    ("ESPORTES", "Esportes"),
                    ("ANIMAIS", "Animais"),
                    ("CIDADES", "Cidades"),
                    ("PESSOAS", "Pessoas"),
                    ("TECNOLOGIA", "Tecnologia"),
                    ("OUTROS", "Outros"),
                ],
                default="",
                max_length=50,
            ),
        ),
    ]
