# Generated by Django 5.2.5 on 2025-09-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0004_alter_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=False),
        ),
    ]
