# Generated by Django 5.2.5 on 2025-10-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0008_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
